### PR TITLE
Prevent AzureMachinePool.SpotVMOptions changes

### PR DESCRIPTION
**Pull request by tuommaki**
Disallow changes to `AzureMachinePool.Spec.Template.SpotVMOptions` on
UPDATE. Changing Spot VM configuration would require special node
rolling strategy for Spot VM Node Pools and this is unsupported for now.

Towards https://github.com/giantswarm/giantswarm/issues/15312

### CODE REVIEW

**Review by whites11 — APPROVED** [review]
LGTM

**Review by axbarsan — APPROVED** [review]
🎩

**Review by whites11 — APPROVED** [review]
Yeah

**Comment by tuommaki** [comment]
Briefly tested on `ghost`. No surprises came up.

**Pull request merged**
